# Generated by Django 3.2 on 2024-12-20 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 18, 45, 10, 140014, tzinfo=utc)),
        ),
    ]
